### ISSUE TITLE
Failures with pgjdbc build

### ISSUE THREAD

**Issue by sualeh** [jackdb/pgjdbc-test-vm#2]
@sehrope - I am getting the following errors when testing with the VM, after my changes in the pull request I submitted. Any ideas on what I can try? The interesting thing is that my VM host is "172.28.128.5", not "172.28.128.1".

```
Tests run: 4324, Failures: 1, Errors: 1, Skipped: 10, Time elapsed: 642.999 sec <<< FAILURE! - in org.postgresql.test.jdbc2.Jdbc2TestSuite
testConcurrentReplace(org.postgresql.test.jdbc2.BlobTransactionTest)  Time elapsed: 0.292 sec  <<< ERROR!
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "172.28.128.1", user "postgres", database "test", SSL on
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.postgresql.test.TestUtil.openPrivilegedDB(TestUtil.java:289)
        at org.postgresql.test.jdbc2.BlobTransactionTest.setUp(BlobTransactionTest.java:53)

testLockReleaseOnCancelFailure(org.postgresql.test.jdbc2.CopyTest)  Time elapsed: 0.522 sec  <<< FAILURE!
java.lang.AssertionError: cancelCopy should have thrown an exception
        at org.junit.Assert.fail(Assert.java:88)
        at org.postgresql.test.jdbc2.CopyTest.testLockReleaseOnCancelFailure(CopyTest.java:377)
```

**Comment by sehrope** [comment]
The "host" in that error message is the pgjdbc client initiating the connection to the PG server running in the VM. The VM sees the inbound TCP traffic coming from 172.28.128.1 so that's the IP that the pg_hba.conf is validated against.

Since port forwarding is enabled you should not need to use a specific IP address. Port 100XY on localhost of the machine running the VM will be forwarded to whatever the dynamic IP address is of the VM.

I'm able to reproduce the two errors in CopyTest and BlobTransactionTest. They're both happening because those tests use the super user connection. If you change the credentials in build.local.properties for the privileged user to match the default one (i.e. test/test for the username password) then the CopyTest will succeed as all it is doing is terminating a connection owned by the same user.

The BlobTransaction test involves creating C language functions which requires a true super user. To get that to run with the test VM we'll need to expose a separate super user as well. I'm going to add that to the VM and push an update.

**Comment by sualeh** [comment]
Thanks, @sehrope - I will give it one more try

**Comment by sualeh** [comment]
@sehrope - thanks for getting me this far. Almost there.

I am getting the following failures:

1. I used port 100XY on localhost. However, the VM sees my host as "10.0.2.2". I tried adding `host all all 0.0.0.0/0 trust` but it did not seem to help. Any ideas? (See details below.)

2. Please could you give me more information on what user credentials to use in `build.local.properties`  for `org.postgresql.test.jdbc2.CopyTest`? That is, can you suggest the contents of `build.local.properties`?

```
Tests run: 4324, Failures: 1, Errors: 1, Skipped: 10, Time elapsed: 464.261 sec <<< FAILURE! - in org.postgresql.test.jdbc2.Jdbc2TestSuite
testConcurrentReplace(org.postgresql.test.jdbc2.BlobTransactionTest)  Time elapsed: 0.123 sec  <<< ERROR!
org.postgresql.util.PSQLException: FATAL: no pg_hba.conf entry for host "10.0.2.2", user "postgres", database "test", SSL on
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:514)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.postgresql.test.TestUtil.openPrivilegedDB(TestUtil.java:289)
        at org.postgresql.test.jdbc2.BlobTransactionTest.setUp(BlobTransactionTest.java:53)

testLockReleaseOnCancelFailure(org.postgresql.test.jdbc2.CopyTest)  Time elapsed: 0.11 sec  <<< FAILURE!
java.lang.AssertionError: cancelCopy should have thrown an exception
        at org.junit.Assert.fail(Assert.java:88)
        at org.postgresql.test.jdbc2.CopyTest.testLockReleaseOnCancelFailure(CopyTest.java:377)

				
Results :

Failed tests:
  CopyTest.testLockReleaseOnCancelFailure:377 cancelCopy should have thrown an exception
Tests in error:
  BlobTransactionTest.setUp:53 » PSQL FATAL: no pg_hba.conf entry for host "10.0...

Tests run: 5442, Failures: 1, Errors: 1, Skipped: 48
```

**Comment by sehrope** [comment]
Try destroying the entire VM (via "vagrant destroy") and rebuilding it from scratch to ensure you have the latest version. It shouldn't require any special manual config after that.

The values for `build.local.properties` that point to the VM are in the README: https://github.com/jackdb/pgjdbc-test-vm#how-do-i-use-it-to-test-the-jdbc-driver

I've tested locally with a slightly modified version of that which also includes spoofing the replication test servers with the same as the primary (which passes *some* of the replica tests but not all of them):

```
#### My build.local.propeties
# Point at PG version 10 on the VM through the localhost port map (username and password etc is the same as build.properties):
server=localhost
port=10010

# This is the super user for the C-language function tests:
privilegedUser=test_super
privilegedPassword=test

# Pretend our primary is also a replica (You can probably ignore this)
secondaryServer=localhost
secondaryPort=10010
secondaryServer2=localhost
secondaryPort2=10010
```

I'd ignore any replica related test issues. The other ones you mention (CopyTest and the Blob related one) should both pass with the config outlined in the README.

**Comment by sualeh** [comment]
Yay! I got it to work! Thanks, @sehrope!
